# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
# Run `copier update` in the scaffolded repo to pull template improvements.
_src_path: ./scaffolding/copier-template
cloud_provider: azure
description: ''
repo_name: azure-iac-repo-test
workspace_name: default

